[package]
name = "line_adjustment"
version = "0.1.0"
authors = ["Vlad Dyachenko"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
